version: '3'
services:
  mongo-db:
    image: 'mongo'
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
  car-rental-gateway-pii-uk:
    image: 'sanjeev1dutta/customer-pii'
    environment:
      PORT: 4000
      DB_URL: 'mongodb://mongo-db:27017/carrental1'
      JWT_SECRET: 'topSecret51'
    ports:
      - '4000:4000'
  car-rental-gateway-pii-us:
    image: 'sanjeev1dutta/customer-pii'
    environment:
      PORT: 5000
      DB_URL: 'mongodb://mongo-db:27017/carrental2'
      JWT_SECRET: 'topSecret51'
    ports:
      - '5000:5000'
    depends_on:
      - mongo-db
  car-rental-gateway:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      PORT: 3000
      JWT_SECRET: 'topSecret51'
      UK_URL: 'http://car-rental-gateway-pii-uk:4000/customers'
      US_URL: 'http://car-rental-gateway-pii-us:5000/customers'
    ports:
      - '3000:3000'
    depends_on:
      - mongo-db
      - car-rental-gateway-pii-us
      - car-rental-gateway-pii-uk
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=qwerty
    ports:
      - 8081:8081
    depends_on:
      - redis
# version: "3"
# services:
#   mongo-db:
#     image: "mongo"
#   car-rental-gateway:
#     build: .
#     ports:
#       - "3001:3001"
#   car-rental-gateway-pii-uk:
#     image: "94714f3fa5e4"
#     ports:
#       - "4000:4000"
#   car-rental-gateway-pii-us:
#     image: "94714f3fa5e4"
#     ports:
#       - "5000:5000"
